
services:
  rag_app:
    image: parami2000/youtube-url-qa-bot:latest
    container_name: youtube_rag_backend
    ports:
      - "8001:8000"   # Expose backend API
    volumes:
      - ./chroma_db:/app/chroma_db:rw  
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    image: parami2000/youtube-rag-frontend:latest
    container_name: youtube_rag_frontend
    ports:
      - "3000:3000"   # Expose frontend UI
    depends_on:
      - rag_app
